### ISSUE TITLE
"todense" is not recognized for h5ad input 

### ISSUE THREAD

**Issue by GangLiTarheel** [google-research/large_scale_mmdma#1]
Hi,
I am trying to load h5ad format data as input and getting the following error:
`../lsmmdma/data/data_pipeline.py", line 126, in load
    data = data.X.todense()
AttributeError: 'numpy.ndarray' object has no attribute 'todense'`
I checked this [link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.todense.html)  for todense. I think you need to `import scipy` and call `scipy.sparse.csc_matrix.todense`?
BTW, should **lsmmdma** check if the input is a sparse matrix? If the input has been a dense matrix already, **lsmmdma** might not need to force it to be dense again.

**Comment by LaetitiaPapaxanthos** [comment]
Thank you Gang for your comment, I will look into shortly it and come back to you.

**Comment by LaetitiaPapaxanthos** [comment]
I modified the function to load the data to take into account these cases. Feel free to reopen the issues if you encounter other problems.
